export const ENV = {
  JWT: {
    ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
    ACCESS_TOKEN_EXPIRATION_TIME: 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  },
  COOKIE: {
    SECRET: 'SECRET_COOKIE',
  },
};
